/**:
    ros__parameters:
        map_frame_id: "map"
        odom_frame_id: "odom_r1"
        robot_frame_id: "chassis_r1"
        use_odom_tf_only: false

        lookahead_distance: 0.8
        brake_ratio: 1.0

        walk_kp: 3.0
        walk_ki: 0.001
        walk_kd: 0.0
        walk_max_vel: 2.0
        walk_vel_filter: 0.5
        walk_goal_tolerance: 0.04
        
        rotate_kp: 2.5
        rotate_ki: 0.0
        rotate_kd: 0.0
        rotate_max_vel: 1.2
        rotate_goal_tolerance: 0.035
        
        twist_topic_name: "cmd_vel"
        path_topic_name: "path"
        irob_status_topic_name: "irob_stat"
        irob_cmd_topic_name: "irob_cmd"
