/r1/irob_maneuv3r_r1:
    ros__parameters:
        # TF2 related parameters
        map_frame_id: "map"
        odom_frame_id: "odom"
        robot_frame_id: "base_link_r1"
        use_odom_tf_only: false
        
        # Walk controller parameters
        # Walk min-max parameters
        walk_max_accel: 0.2
        walk_max_vel: 2.5
        walk_min_vel: 0.1
        
        # Walk pure-pursuit parameters
        lookahead_distance: 0.6
        lookahead_ff_points: 15
        
        # Walk PID parameters
        walk_kp: 2.2
        walk_ki: 0.001
        walk_kd: 0.01
        
        # Rotate controller parameters
        # Rotate min-max parameters
        rotate_max_vel: 1.1
        
        # Rotate PID parameters
        rotate_kp: 2.3
        rotate_ki: 0.0001
        rotate_kd: 0.0
        
        # Goal checker parameter
        walk_goal_tolerance: 0.04
        rotate_goal_tolerance: 0.035